name: "Podcast Generator"
author: "Jose Morales"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    description: Commiter's email
    default: ${{ github.actor }}@localhost
  name: 
    description: Commiter's name
    required: true
    default: ${{ github.actor }}
